server:
  port: 9020

spring:
  application:
    name: "server-eureka"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8888/"

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

